# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('nct_number', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('recruitment', models.CharField(max_length=255)),
                ('study_results', models.CharField(max_length=255)),
                ('conditions', models.CharField(max_length=255)),
                ('interventions', models.CharField(max_length=255)),
                ('sponsor', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('phases', models.CharField(blank=True, max_length=255, null=True)),
                ('enrolment', models.CharField(max_length=255)),
                ('funded_by', models.CharField(max_length=255)),
                ('study_types', models.CharField(max_length=255)),
                ('study_designs', models.CharField(max_length=255)),
                ('other_ids', models.CharField(max_length=255)),
                ('first_received', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('completion_date', models.CharField(max_length=255)),
                ('last_updated', models.CharField(max_length=255)),
                ('last_verified', models.CharField(max_length=255)),
                ('results_first_received', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=255)),
                ('primary_completion_date', models.CharField(max_length=255)),
                ('outcome_measures', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
